#                     :+*=:.
#                  :=*@@@@@@@#
#               :%@@@@@@@@@@@@=
#              -@@@@@@@@@@@@@@%
#             .#@@%+*#%@@@@@@@@:
#             :@@@:    =::=%@@+
#             :@@-         -@@:
#              %@=          =@-
#             .%%+@@%@-+@@##=:
#              =%:     =   :=.            developed by mindamagov
#               =@=  @+-=  :                (t.me/javacrime)
#                *+   @*   .:
#                 @%@@@%=:#@-                any questions?
#                =@@@- .-@@*=-           write to me on telegram
#              :%*@@@@@@@@+ .-:
#           =#@@@+ @@@@@@:  .  *+==:
#      .+%@@@@@@@* .@@@-     =@@-:..
#    +@@@@@@@@@@@*:@@@@=    :@@*::.
#   =@@@@@@@@@@@@%. *@@=:==  @@@ .--
#   *@@@@@@@@@@@@%   @@:     -*
#   %@@@@@@@@@@@@%.   @:
# :@@@@@@@@@@@@@@:  *@:


kill-message:
  enabled: true
  format: "&cüó° &f%killer% —É–±–∏–ª &f%victim% &c‚ò†Ô∏è"
anti-ads:
  enabled: true
  error: '&cmindamagov.lol ¬ßf–í–∞—à–µ —Å–æ–æ–±—â–µ–Ω–∏–µ –±—ã–ª–æ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–æ.'
  whitelist-players:
    - "mindamagov"
  blockwords:
    - "ru"
    - ".ru"
    - "r!u"
    - "r.u"
    - "ru!"
    - "play"
    - ".play"
    - "p!lay"
    - "pl!ay"
    - "pla!y"
    - "play!"
    - "core"
    - ".core"
    - "c.ore"
    - "co.re"
    - "cor.e"
    - "core."
    - "!core"
    - "c!ore"
    - "cor!e"
    - "xyz"
    - ".xyz"
    - "x.yz"
    - "x!yz"
    - "!xyz"
    - "xy!z"
    - "mc"
    - ".mc"
    - "m!c"
    - "m.c"
    - "net"
    - ".net"
    - "n!et"
    - "ne!t"
join-text:
  enabled: true
  lines:
    - ''
    - ' &cmindamagov.lol'
    - ' ¬ßf–î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –Ω–∞ —Å–µ—Ä–≤–µ—Ä!'
    - ''
block-place:
  enabled: true
  send-message: true
  message: '&cmindamagov.lol &f–í—ã –Ω–µ –º–æ–∂–µ—Ç–µ &c—Å—Ç–∞–≤–∏—Ç—å&f –¥–∞–Ω–Ω—ã–π &c–±–ª–æ–∫!'
  whitelist-players:
    - "mindamagov"
  whitelist-worlds:
    - world
  blacklist-worlds:
    - afk
  blocks-whitelist:
    - COBWEB
    - ORANGE_CONCRETE
    - RED_CONCRETE_POWDER
block-break:
  enabled: true
  send-message: true
  message: '&cmindamagov.lol &f–í—ã –Ω–µ –º–æ–∂–µ—Ç–µ &c—Å–ª–æ–º–∞—Ç—å&f –¥–∞–Ω–Ω—ã–π &c–±–ª–æ–∫!'
  whitelist-players:
    - "mindamagov"
  whitelist-worlds:
    - world
  blacklist-worlds:
    - afk
  blocks-whitelist:
    - DIAMOND_ORE
    - DIAMOND_BLOCK
    - EMERALD_ORE
    - EMERALD_BLOCK
    - ORANGE_GLAZED_TERRACOTTA
    - BLUE_GLAZED_TERRACOTTA
    - LIME_GLAZED_TERRACOTTA
    - PINK_GLAZED_TERRACOTTA
    - YELLOW_GLAZED_TERRACOTTA
    - BROWN_GLAZED_TERRACOTTA
map-cleaner:
  enabled: true
  blocks:
    - OAK_WOOD
    - COBWEB
    - GLASS
    - WHITE_WOOL
  whitelist-players:
    - "mindamagov"
  whitelist-worlds:
    - world
  time-to-clear: 1 # –≤—Ä–µ–º—è —É–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è –≤ —Å–µ–∫—É–Ω–¥–∞—Ö
  send-message-on-remove: true
  remove-message: '&cmindamagov.lol &f–í–∞—à –±–ª–æ–∫ –∏—Å—á–µ–∑'